services:
  - type: web
    name: selfcast-cms-admin
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://Testuser:Testing123456@payloadonetorulethemall.9t4fnbt.mongodb.net/payload-cms?retryWrites=true&w=majority&appName=Payloadonetorulethemall
      - key: PAYLOAD_SECRET
        value: selfcast-studios-7af51d0c-ac48-4845-a41a
      - key: NODE_ENV
        value: production
      - key: PAYLOAD_CONFIG_PATH
        value: dist/payload.config.js
      - key: PORT
        value: 10000
      - key: PAYLOAD_PUBLIC_SERVER_URL
        value: https://selfcast-cms-admin.onrender.com
      - key: DEBUG
        value: payload*
    autoDeploy: true
